name: Frontend CI

on:
    push:
    pull_request:

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install
              working-directory: .

            - name: Check formatting
              run: pnpx prettier --write .
              working-directory: .

    lint:
        needs: format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install
              working-directory: .

            - name: Lint
              run: pnpm run lint
              working-directory: .
